package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnderecoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAllPropertiesEquals(Endereco expected, Endereco actual) {
        assertEnderecoAutoGeneratedPropertiesEquals(expected, actual);
        assertEnderecoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAllUpdatablePropertiesEquals(Endereco expected, Endereco actual) {
        assertEnderecoUpdatableFieldsEquals(expected, actual);
        assertEnderecoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAutoGeneratedPropertiesEquals(Endereco expected, Endereco actual) {
        assertThat(expected)
            .as("Verify Endereco auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoUpdatableFieldsEquals(Endereco expected, Endereco actual) {
        assertThat(expected)
            .as("Verify Endereco relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getLogradouro()).as("check logradouro").isEqualTo(actual.getLogradouro()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getComplemento()).as("check complemento").isEqualTo(actual.getComplemento()))
            .satisfies(e -> assertThat(e.getReferencia()).as("check referencia").isEqualTo(actual.getReferencia()))
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()))
            .satisfies(e -> assertThat(e.getEstado()).as("check estado").isEqualTo(actual.getEstado()))
            .satisfies(e -> assertThat(e.getPais()).as("check pais").isEqualTo(actual.getPais()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoUpdatableRelationshipsEquals(Endereco expected, Endereco actual) {
        assertThat(expected)
            .as("Verify Endereco relationships")
            .satisfies(e -> assertThat(e.getPessoa()).as("check pessoa").isEqualTo(actual.getPessoa()));
    }
}
