package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstabelecimentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstabelecimentoAllPropertiesEquals(Estabelecimento expected, Estabelecimento actual) {
        assertEstabelecimentoAutoGeneratedPropertiesEquals(expected, actual);
        assertEstabelecimentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstabelecimentoAllUpdatablePropertiesEquals(Estabelecimento expected, Estabelecimento actual) {
        assertEstabelecimentoUpdatableFieldsEquals(expected, actual);
        assertEstabelecimentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstabelecimentoAutoGeneratedPropertiesEquals(Estabelecimento expected, Estabelecimento actual) {
        assertThat(expected)
            .as("Verify Estabelecimento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstabelecimentoUpdatableFieldsEquals(Estabelecimento expected, Estabelecimento actual) {
        assertThat(expected)
            .as("Verify Estabelecimento relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstabelecimentoUpdatableRelationshipsEquals(Estabelecimento expected, Estabelecimento actual) {
        assertThat(expected)
            .as("Verify Estabelecimento relationships")
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()));
    }
}
