package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OperacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperacaoAllPropertiesEquals(Operacao expected, Operacao actual) {
        assertOperacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertOperacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperacaoAllUpdatablePropertiesEquals(Operacao expected, Operacao actual) {
        assertOperacaoUpdatableFieldsEquals(expected, actual);
        assertOperacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperacaoAutoGeneratedPropertiesEquals(Operacao expected, Operacao actual) {
        assertThat(expected)
            .as("Verify Operacao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperacaoUpdatableFieldsEquals(Operacao expected, Operacao actual) {
        assertThat(expected)
            .as("Verify Operacao relevant properties")
            .satisfies(e -> assertThat(e.getArquivoImagem()).as("check arquivoImagem").isEqualTo(actual.getArquivoImagem()))
            .satisfies(e ->
                assertThat(e.getArquivoImagemContentType())
                    .as("check arquivoImagem contenty type")
                    .isEqualTo(actual.getArquivoImagemContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOperacaoUpdatableRelationshipsEquals(Operacao expected, Operacao actual) {
        // empty method
    }
}
