package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PessoaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAllPropertiesEquals(Pessoa expected, Pessoa actual) {
        assertPessoaAutoGeneratedPropertiesEquals(expected, actual);
        assertPessoaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAllUpdatablePropertiesEquals(Pessoa expected, Pessoa actual) {
        assertPessoaUpdatableFieldsEquals(expected, actual);
        assertPessoaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaAutoGeneratedPropertiesEquals(Pessoa expected, Pessoa actual) {
        assertThat(expected)
            .as("Verify Pessoa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaUpdatableFieldsEquals(Pessoa expected, Pessoa actual) {
        assertThat(expected)
            .as("Verify Pessoa relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaUpdatableRelationshipsEquals(Pessoa expected, Pessoa actual) {
        assertThat(expected)
            .as("Verify Pessoa relationships")
            .satisfies(e -> assertThat(e.getTipoPessoa()).as("check tipoPessoa").isEqualTo(actual.getTipoPessoa()));
    }
}
