package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoAutomovelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutomovelAllPropertiesEquals(TipoAutomovel expected, TipoAutomovel actual) {
        assertTipoAutomovelAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoAutomovelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutomovelAllUpdatablePropertiesEquals(TipoAutomovel expected, TipoAutomovel actual) {
        assertTipoAutomovelUpdatableFieldsEquals(expected, actual);
        assertTipoAutomovelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutomovelAutoGeneratedPropertiesEquals(TipoAutomovel expected, TipoAutomovel actual) {
        assertThat(expected)
            .as("Verify TipoAutomovel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutomovelUpdatableFieldsEquals(TipoAutomovel expected, TipoAutomovel actual) {
        assertThat(expected)
            .as("Verify TipoAutomovel relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getGrupo()).as("check grupo").isEqualTo(actual.getGrupo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoAutomovelUpdatableRelationshipsEquals(TipoAutomovel expected, TipoAutomovel actual) {
        // empty method
    }
}
