package tcc.leroma.pivestudo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoPessoaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoPessoaAllPropertiesEquals(TipoPessoa expected, TipoPessoa actual) {
        assertTipoPessoaAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoPessoaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoPessoaAllUpdatablePropertiesEquals(TipoPessoa expected, TipoPessoa actual) {
        assertTipoPessoaUpdatableFieldsEquals(expected, actual);
        assertTipoPessoaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoPessoaAutoGeneratedPropertiesEquals(TipoPessoa expected, TipoPessoa actual) {
        assertThat(expected)
            .as("Verify TipoPessoa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoPessoaUpdatableFieldsEquals(TipoPessoa expected, TipoPessoa actual) {
        assertThat(expected)
            .as("Verify TipoPessoa relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getGrupo()).as("check grupo").isEqualTo(actual.getGrupo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoPessoaUpdatableRelationshipsEquals(TipoPessoa expected, TipoPessoa actual) {
        // empty method
    }
}
